//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebys10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EbysVol9Entities : DbContext
    {
        public EbysVol9Entities()
            : base("name=EbysVol9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GIVENCOURSES> GIVENCOURSES { get; set; }
        public virtual DbSet<MENTOR> MENTOR { get; set; }
        public virtual DbSet<SEMESTERCOURSE> SEMESTERCOURSE { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<TEACHER> TEACHER { get; set; }
        public virtual DbSet<TAKENCOURSES> TAKENCOURSES { get; set; }
    }
}
