//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebys10
{
    using System.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class GIVENCOURSES
    {
        public string GTeacherId { get; set; }
        public string GCourseId { get; set; }
        public int Credit { get; set; }
    
        public virtual SEMESTERCOURSE SEMESTERCOURSE { get; set; }
        public virtual TEACHER TEACHER { get; set; }

        public List<string> getStudents(string courseId)
        {
            List<string> a = new List<string>();
            using (var db = new EbysVol9Entities())
            {
                var result = from k in db.TAKENCOURSES
                             where k.TCourseId == courseId
                             select new
                             {
                                 k.TStudenId

                             };
                foreach (var item in result)
                {
                    a.Add(item.TStudenId);
                }

            }

            return (a);

        }
    }

   
}
