//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebys10
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTERCOURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEMESTERCOURSE()
        {
            this.TAKENCOURSES = new HashSet<TAKENCOURSES>();
        }
    
        public string CourseId { get; set; }
        public string CourseName { get; set; }
    
        public virtual GIVENCOURSES GIVENCOURSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKENCOURSES> TAKENCOURSES { get; set; }
    }
}
