//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebys10
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Linq;

    public partial class TAKENCOURSES
    {
        public string TStudenId { get; set; }
        public string TCourseId { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual SEMESTERCOURSE SEMESTERCOURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }

        public void saveGrade(string courseId, string studentId, int grade)
        {
            SqlConnection con = new SqlConnection("Data Source = DESKTOP-RUVJ75R; Initial Catalog = EbysVol9; Integrated Security = true");

            con.Open();
            // UPDATE Customers
            //SET ContactName = 'Alfred Schmidt', City = 'Frankfurt'
            //WHERE CustomerID = 1;
                SqlCommand cmd = new SqlCommand("UPDATE TAKENCOURSES SET Grade=@Grade WHERE TCourseId=@TCourseId AND TStudenId=@TStudentId", con);
                cmd.Parameters.AddWithValue("@TCourseId", courseId);
                cmd.Parameters.AddWithValue("@TStudentId", studentId);
                cmd.Parameters.AddWithValue("@Grade", grade);

                
                cmd.ExecuteNonQuery();

            con.Close();

        }
    }
}
