//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebys10
{
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public partial class TEACHER
    {
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
       
            this.GIVENCOURSES = new HashSet<GIVENCOURSES>();
        }
    
        public string TeacherId { get; set; }
        public string TeacherName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIVENCOURSES> GIVENCOURSES { get; set; }
        public List<string> getCourse(string teacherId)
        {
            List<string> a = new List<string>();
            using (var db = new EbysVol9Entities())
            {
                var result = from k in db.GIVENCOURSES
                             where k.GTeacherId == teacherId
                             select new
                             {
                                 k.GCourseId

                            };
                foreach (var item in result)
                 {
                    a.Add(item.GCourseId);
                 }

            }

            return (a);

            //SqlConnection con = new SqlConnection("DESKTOP-RUVJ75R;initial catalog=EbysVol9;integrated security=True");


            //SqlCommand cmd = new SqlCommand("select GCourseId from GIVENCOURSES where GteacherId=@teacherId",con);
            //cmd.Parameters.AddWithValue("@teacherId", teacherId);
            //con.Open();
            //cmd.ExecuteNonQuery();
        }

    }
}
